### ISSUE TITLE
the extension used to work perfectly fine during its release, but now there's a few problems with it

### ISSUE THREAD

**Issue by Hai-Phong** [tungnguyensnk/autofillForm#2]
manifest.json seems to have typo errors? 
![image](https://github.com/tungnguyensnk/autofillForm/assets/112364252/8f7a75a4-797b-4721-b1c9-4489a6e91522)
plus even after changing it, another problem arises: I can't add the *.data file for the extension, it just stays like this 
![image](https://github.com/tungnguyensnk/autofillForm/assets/112364252/f68cb6c9-8b44-42b7-933c-a88270db29cc)
Would really appreaciate it if u can tell me where did it go wrong and the solutions. Much thanks for the amazing extension.
[autofillForm_v1.0.0.zip](https://github.com/tungnguyensnk/autofillForm/files/11642692/autofillForm_v1.0.0.zip)

**Comment by tungnguyensnk** [comment]
Thank you. 'Permission' is incorrect. It should be 'permissions.' Actually, even if it's incorrect, it doesn't matter because Chrome won't read it. The second issue is due to an extra comma in the data file. I have fixed it, so please try again.
