### ISSUE TITLE
Lỗi The form is closed

### ISSUE THREAD

**Issue by thiemcun169** [tungnguyensnk/autofillForm#3]
Anh ơi khi em import file lên thì nó liên chuyển sang trang báo the form is closed, em cố ngồi sửa đoán do lỗi link hay lỗi form chặn tự động điền nhưng chưa được, anh có thể update bản mới được ko ạ?
Em cảm ơn ạ

**Comment by tungnguyensnk** [comment]
do anh chưa update data mới. em dùng thử lại nha.
