### ISSUE TITLE
Data mới kì 20231

### ISSUE THREAD

**Issue by milo-v** [tungnguyensnk/autofillForm#4]
[Pháp luật](https://cdn.discordapp.com/attachments/761182263407935488/1183786667581112370/phapluat20231.data?ex=65899a3f&is=6577253f&hm=587249bf64b97ee656d3dfd91bc64f0becb4b3af3bdd69e360ce7d4a62b565fd&)
[Quy chế](https://cdn.discordapp.com/attachments/761182263407935488/1183786668084441108/quyche20231.data?ex=65899a3f&is=6577253f&hm=090370521cb23a759fdceb8857a7234aadb289f36609908d87499a9075a33b7b&)

**Comment by tungnguyensnk** [comment]
cảm ơn em nhé. anh sắp ra trường nên chắc extension cũng ít được update. em có thể phát triển tiếp được không để anh add em vào.
